[test] feat: reorganise code to adapt test and add media test
nighthaven/The-Endless-universe-codex pull request #6
Opened 2024-10-07 14:16 UTC by nighthaven

2024-10-07 16:20 UTC, jbalieux commented
[api] test: reorganise code to adapt test and add media test

2024-10-07 16:27 UTC, jbalieux commented on src/services/media_services.py
> +class MediaServices:
MediaService

2024-10-07 16:27 UTC, jbalieux commented on src/services/media_services.py
> +        return media
Essaie de créer une vraie class sans méthode static pour la dependence de route

https://fastapi.tiangolo.com/tutorial/dependencies/classes-as-dependencies/#classes-as-dependencies_1

2024-10-08 15:43 UTC, nighthaven commented on src/services/media_services.py
> +        return media
fait dans le dernier commit

2024-10-08 16:37 UTC, jbalieux approved these changes

2024-10-08 16:37 UTC, jbalieux commented on src/services/user_services.py
> +    def get_user(self, email: str) -> User:
`get_user_by_email`

2024-10-08 16:37 UTC, jbalieux requested changes
[test] feat: reorganise code to adapt test and add media test

C'est une feat, c'est un test, c'est une refacto ? Je ne comprend pas le nom de ta pr

2024-10-08 17:34 UTC, merged